### ISSUE TITLE
QDate problem

### ISSUE THREAD

**Issue by ghtmtt** [ghtmtt/DataPlotly#122]
If a column is `date` type the following error appear:

```
Traceback (most recent call last):
  File "/home/matteo/.local/share/QGIS/QGIS3/profiles/matteo/python/plugins/DataPlotly/data_plotly_dialog.py", line 1086, in UpdatePlot
    self.createPlot()
  File "/home/matteo/.local/share/QGIS/QGIS3/profiles/matteo/python/plugins/DataPlotly/data_plotly_dialog.py", line 1034, in createPlot
    self.plot_path = self.plotobject.buildFigure()
  File "/home/matteo/.local/share/QGIS/QGIS3/profiles/matteo/python/plugins/DataPlotly/data_plotly_plot.py", line 665, in buildFigure
    self.raw_plot += plotly.offline.plot(fig, output_type='div', include_plotlyjs=False, show_link=False, config=config)
  File "/usr/lib/python3/dist-packages/plotly/offline/offline.py", line 657, in plot
    '100%', '100%', global_requirejs=False)
  File "/usr/lib/python3/dist-packages/plotly/offline/offline.py", line 348, in _plot_html
    jdata = _json.dumps(figure.get('data', []), cls=utils.PlotlyJSONEncoder)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3/dist-packages/plotly/utils.py", line 168, in encode
    encoded_o = super(PlotlyJSONEncoder, self).encode(o)
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3/dist-packages/plotly/utils.py", line 236, in default
    return _json.JSONEncoder.default(self, obj)
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type QDate is not JSON serializable
```

**Comment by jdugge** [comment]
Workaround from the [related discussion](http://osgeo-org.1560.x6.nabble.com/Data-Ploty-tp5406774p5408181.html) at the QGIS Italian User list:
Instead of using the field directly when configuring the plot, you can convert it to a string first using the expression `to_string("fieldname")`

**Comment by tethysgeco** [comment]
Hi, do you have any updates about Qdate problem? 
Today I've tried to create a scatter plot graph on a layer with date as x and piezometric head (a numeric field) as y and it returned as error: "TypeError: Object of type QDate is not JSON serializable".  The layer is a Postgis view, Qgis 3.4.7
Thanks

**Comment by ghtmtt** [comment]
@tethysgeco did you try the `to_string("fieldname")` expression? We will for sure address this issue, but for the moment you can use this workaround

**Comment by tethysgeco** [comment]
yes, it works. thanks
