### ISSUE TITLE
TypeError: setChecked(self, bool): argument 1 has unexpected type 'NoneType'

### ISSUE THREAD

**Issue by danpejobo** [ghtmtt/DataPlotly#185]
Hi, i got a new problem after upgrading to 3.2: It is linked to this #183 fix, since i had that before upgrading.

It seems to occur when i open a project wich was created before i upgraded this plugin. It does not occur when i start a new project in qgis.

Traceback (most recent call last):
              File "C:\Users\dpe\AppData\Roaming\QGIS\QGIS3\profiles\Daniel\python\plugins\DataPlotly\gui\plot_settings_widget.py", line 1393, in read_project
              self.set_settings(settings)
              File "C:\Users\dpe\AppData\Roaming\QGIS\QGIS3\profiles\Daniel\python\plugins\DataPlotly\gui\plot_settings_widget.py", line 1080, in set_settings
              self.violinBox.setChecked(settings.properties.get('violin_box', None))
             TypeError: setChecked(self, bool): argument 1 has unexpected type 'NoneType'

**Comment by ghtmtt** [comment]
Are you trying to open a project with a plot configuration saved with a previous version of DataPlotly?

**Comment by danpejobo** [comment]
@ghtmtt as far as i remember i never opened DataPlotly in this project. Or at least, i never plotted anything in this project

**Comment by ghtmtt** [comment]
can you try to create a clean qgis profile, download dataplotly in that profile and tell if you still get the error?

**Comment by danpejobo** [comment]
With the new testprofile and the same project as above. I also tried to open 5 different projects with this testprofile, and got the same error message in all BUT one... which seems wierd to me since i never used the plugin in any of these projects

Traceback (most recent call last):
  File "C:\Users\dpe\AppData\Roaming\QGIS\QGIS3\profiles\Daniel\python\plugins\DataPlotly\gui\plot_settings_widget.py", line 1393, in read_project
    self.set_settings(settings)
  File "C:\Users\dpe\AppData\Roaming\QGIS\QGIS3\profiles\Daniel\python\plugins\DataPlotly\gui\plot_settings_widget.py", line 1080, in set_settings
    self.violinBox.setChecked(settings.properties.get('violin_box', None))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'NoneType'

**Comment by ghtmtt** [comment]
fixed in #186
