### ISSUE TITLE
TypeError: Object of type QTime is not JSON serializable

### ISSUE THREAD

**Issue by SKullYeR** [ghtmtt/DataPlotly#275]
Bug description, directly copied from QGIS Python error console:

```
2021-11-09T12:39:41     WARNING    Traceback (most recent call last):
              File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\gui\plot_settings_widget.py", line 1230, in create_plot
              self.plot_path = plot_factory.build_figures(self.ptype, pl)
              File "C:\Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\core\plot_factory.py", line 740, in build_figures
              self.raw_plot += plotly.offline.plot(figures, output_type='div', include_plotlyjs=False, show_link=False,
              File "D:\tools\QGIS\apps\Python39\lib\site-packages\plotly\offline\offline.py", line 601, in plot
              return pio.to_html(
              File "D:\tools\QGIS\apps\Python39\lib\site-packages\plotly\io\_html.py", line 137, in to_html
              jdata = json.dumps(
              File "D:\tools\QGIS\apps\Python39\lib\json\__init__.py", line 234, in dumps
              return cls(
              File "D:\tools\QGIS\apps\Python39\lib\site-packages\_plotly_utils\utils.py", line 45, in encode
              encoded_o = super(PlotlyJSONEncoder, self).encode(o)
              File "D:\tools\QGIS\apps\Python39\lib\json\encoder.py", line 199, in encode
              chunks = self.iterencode(o, _one_shot=True)
              File "D:\tools\QGIS\apps\Python39\lib\json\encoder.py", line 257, in iterencode
              return _iterencode(o, 0)
              File "D:\tools\QGIS\apps\Python39\lib\site-packages\_plotly_utils\utils.py", line 115, in default
              return _json.JSONEncoder.default(self, obj)
              File "D:\tools\QGIS\apps\Python39\lib\json\encoder.py", line 179, in default
              raise TypeError(f'Object of type {o.__class__.__name__} '
             TypeError: Object of type QTime is not JSON serializable
```

**To Reproduce**
1. click on 'Plugins'
2. search for 'Data Plotly'
3. click "install plugin" down right corner
4. Load .geojson with feature collection into QGIS
5. click on 'Plugins'
6. click on 'Data Plotly'
7. 
![image](https://user-images.githubusercontent.com/70097842/140920527-0f5a2566-e03a-4a44-a2f7-ee57006d4c80.png)
8. Create Plot

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 vers.: 20H2 (OS Build 19042.1288)
 - QGIS release QGIS 3.16.11
 - DataPlotly release 3.8.1

**Comment by ghtmtt** [comment]
not sure about that, but can you convert the `Time` field in a `Datetime` one?

**Comment by ghtmtt** [comment]
@SKullYeR do you have any feedback on this? Can I close the issue?

**Comment by SKullYeR** [comment]
close it, ty

 
 

Gesendet: Mittwoch, 13. April 2022 um 09:36 Uhr
Von: "Matteo Ghetta" ***@***.***>
An: "ghtmtt/DataPlotly" ***@***.***>
Cc: "SKullYeR" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [ghtmtt/DataPlotly] TypeError: Object of type QTime is not JSON serializable (Issue #275)


 

@SKullYeR do you have any feedback on this? Can I close the issue?
