### ISSUE TITLE
Encountering 'AttributeError: module 'pandas' has no attribute 'Series'' error while developing Hypsometric curves graphs using DataPlotly plugin in QGIS

### ISSUE THREAD

**Issue by mfaisalhanif** [ghtmtt/DataPlotly#312]
I am attempting to develop Hypsometric curves graphs in QGIS using the Data Plotly plugin, but I'm encountering the following error: 

```
line 176, in is_homogeneous_array
              or (pd and isinstance(v, (pd.Series, pd.Index)))
             AttributeError: module 'pandas' has no attribute 'Series'
```

I've tried upgrading my Pandas version, but the problem persists. Can you provide any guidance on how to resolve this issue? Thank you for your assistance.

**Comment by ghtmtt** [comment]
can you please paste the entire stack trace and share a minimal dataset?

**Comment by mfaisalhanif** [comment]
Thank you for your response. I developed the area vs elevation file while using the QGIS hypsometric function and then tried to plot it using dataplotly. The error I got is the following 

`2023-03-01T10:44:28     WARNING    Traceback (most recent call last):
              File "C:\Users/M Faisal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\gui\plot_settings_widget.py", line 1296, in create_plot
              plot_factory = self.create_plot_factory()
              File "C:\Users/M Faisal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\gui\plot_settings_widget.py", line 1253, in create_plot_factory
              plot_factory = PlotFactory(settings, visible_region=visible_region)
              File "C:\Users/M Faisal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\core\plot_factory.py", line 113, in __init__
              self.rebuild()
              File "C:\Users/M Faisal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\core\plot_factory.py", line 430, in rebuild
              self.trace = self._build_trace()
              File "C:\Users/M Faisal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\core\plot_factory.py", line 447, in _build_trace
              return PlotFactory.PLOT_TYPES[self.settings.plot_type].create_trace(self.settings)
              File "C:\Users/M Faisal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\core\plot_types\scatter.py", line 43, in create_trace
              return [graph_objs.Scatter(
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\plotly\graph_objs\_scatter.py", line 2926, in __init__
              self["customdata"] = _v
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\plotly\basedatatypes.py", line 4534, in __setitem__
              self._set_prop(prop, value)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\plotly\basedatatypes.py", line 4847, in _set_prop
              val = validator.validate_coerce(val)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\_plotly_utils\basevalidators.py", line 386, in validate_coerce
              elif is_homogeneous_array(v):
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\_plotly_utils\basevalidators.py", line 176, in is_homogeneous_array
              or (pd and isinstance(v, (pd.Series, pd.Index)))
             AttributeError: module 'pandas' has no attribute 'Series'`

The data file is also attached. I am grateful for your time and help. 
[Trentino_hypsometric.csv](https://github.com/ghtmtt/DataPlotly/files/10859458/Trentino_hypsometric.csv)

**Comment by ghtmtt** [comment]
I cannot confirm the issue. I loaded the dataset and I can correctly create the plot with the following parameters:

![ksnip_20230301-114810](https://user-images.githubusercontent.com/2884884/222118146-3ac68ba9-92b6-428e-9e43-443f631dee68.png)

![image](https://user-images.githubusercontent.com/2884884/222118211-4fc308c3-5abb-4f0a-8a80-c52959d0f406.png)

**Comment by mfaisalhanif** [comment]
That's exactly what I want. Let me try to reinstall both the QGIS and dataplotly. Maybe that could help. 

Thank you for your time and help.
