### ISSUE TITLE
DataPlotly 4.0.1 "Pie hole" issue

### ISSUE THREAD

**Issue by pedrogeo** [ghtmtt/DataPlotly#324]
Hi,

I have a qgis project where I have use _DataPlotly_ inside report. Since the last _DataPlotly_ update (4.0.1), I have an error message that appears when I want to export my report to pdf :

```
KeyError: 'pie_hole' 
Traceback (most recent call last):
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\layouts\plot_layout_item.py", line 158, in draw
    self.load_content()
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\layouts\plot_layout_item.py", line 224, in load_content
    self.web_page.mainFrame().setHtml(self.create_plot(), base_url)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\layouts\plot_layout_item.py", line 182, in create_plot
    plot_factory = PlotFactory(self.plot_settings[0], self, polygon_filter=polygon_filter)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\core\plot_factory.py", line 116, in __init__
    self.rebuild()
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\core\plot_factory.py", line 444, in rebuild
    self.trace = self._build_trace()
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\core\plot_factory.py", line 461, in _build_trace
    return PlotFactory.PLOT_TYPES[self.settings.plot_type].create_trace(self.settings)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\core\plot_types\pie.py", line 43, in create_trace
    hole=settings.properties['pie_hole']
KeyError: 'pie_hole'


Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.30.3-'s-Hertogenbosch 's-Hertogenbosch, 2411cec1
```

 - OS: Windows 10 22H2
 - QGIS release [e.g. QGIS 3.30.3]
 - DataPlotly release [e.g. 4.0.1]

Do you have an idea, other than using the previous version of the plugin ? Has anyone encountered the same problem ?

Pierre

**Comment by ghtmtt** [comment]
I'll make some tests and let you know. Probably a fix like this https://github.com/ghtmtt/DataPlotly/pull/206/files should work (@jdlom)

**Comment by jdlom** [comment]
@pedrogeo can you share a minimal qgis project to reproduce this bug ?  @ghtmtt Indeed I think this fix should work. Can you assign me this issue ?

**Comment by ghtmtt** [comment]
> @pedrogeo can you share a minimal qgis project to reproduce this bug ? @ghtmtt Indeed I think this fix should work. Can you assign me this issue ?

sure! thanks!

**Comment by pedrogeo** [comment]
> @pedrogeo can you share a minimal qgis project to reproduce this bug ? @ghtmtt Indeed I think this fix should work. Can you assign me this issue ?

@jdlom I update DataPlotly to the 4.0.2 and there is another bug :

`Traceback (most recent call last):
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\layouts\plot_layout_item.py", line 157, in draw
    self.load_content()
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\layouts\plot_layout_item.py", line 223, in load_content
    self.web_page.mainFrame().setHtml(self.create_plot(), base_url)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\layouts\plot_layout_item.py", line 181, in create_plot
    plot_factory = PlotFactory(self.plot_settings[0], self, polygon_filter=polygon_filter)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\core\plot_factory.py", line 115, in __init__
    self.rebuild()
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\core\plot_factory.py", line 443, in rebuild
    self.trace = self._build_trace()
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\core\plot_factory.py", line 460, in _build_trace
    return PlotFactory.PLOT_TYPES[self.settings.plot_type].create_trace(self.settings)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\qgis_3_30/python/plugins\DataPlotly\core\plot_types\pie.py", line 42, in create_trace
[dataplotly.zip](https://github.com/ghtmtt/DataPlotly/files/11870102/dataplotly.zip)

    hole=settings.get('pie_hole', 0)
AttributeError: 'PlotSettings' object has no attribute 'get'`

The minimal project in attachment.

**Comment by jdlom** [comment]
Sorry. This is my mistake. I need holidays. Could you give me a project.

**Comment by pedrogeo** [comment]
The minimal project : [https://github.com/ghtmtt/DataPlotly/files/11870109/dataplotly.zip]

**Comment by pedrogeo** [comment]
I tested your fix on my DataPlotly install and it works. Thanks for your work.

**Comment by jdlom** [comment]
Thanks for your feedback @pedrogeo
