### ISSUE TITLE
Qgis 3.34.0 (ubuntu) - ModuleNotFoundError: No module named 'pandas' 

### ISSUE THREAD

**Issue by image80** [ghtmtt/DataPlotly#340]
Good afternoon,
I work with Qgis 3.34.0-Prizren on Ubuntu. 
I would like test and use this plugin. 

I succeed in installing this plugin via the qgis plugin manager. But when i try to enable it still into the plugin manager, i have an error message saying : 

In advance, thanks so much for your help.

```
Impossible de charger l'extension 'DataPlotly' provoque une erreur lors de l'appel à sa méthode classFactory() 

**ModuleNotFoundError: No module named 'pandas'** 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/__init__.py", line 33, in classFactory
    from .data_plotly import DataPlotly
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly.py", line 36, in 
    from DataPlotly.processing.dataplotly_provider import DataPlotlyProvider
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/processing/dataplotly_provider.py", line 24, in 
    from DataPlotly.processing.dataplotly_scatterplot import DataPlotlyProcessingScatterPlot
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/processing/dataplotly_scatterplot.py", line 43, in 
    import pandas as pd
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
**ModuleNotFoundError: No module named 'pandas'**


Version de Python : 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] 
Version de QGIS : 3.34.0-Prizren Prizren, ffbdd678812 

Chemin Python :
/usr/share/qgis/python
/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python
/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python
/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/forms
/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SentinelHub/external/requests_oauthlib-1.3.1-py2.py3-none-any.whl
/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview
/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/res
```

**Comment by ghtmtt** [comment]
dataplotly plugin relies on the `pandas` python library. Depending on your OS you have to install it by yourself (Linux and OSX) or use the QGIS Standalone installer or the OSGEO4W installer choosing qgis-full (Windows).

**Comment by ghtmtt** [comment]
fixed by https://github.com/ghtmtt/DataPlotly/pull/332
