### ISSUE TITLE
DataPlotly does not work in QGIS 3.40.1

### ISSUE THREAD

**Issue by pigreco** [ghtmtt/DataPlotly#365]
When starting QGIS 3.40.1 the message attached below appears:

```
Impossibile caricare il plugin 'DataPlotly' a causa di un errore chiamando il metodo classFactory() 

TypeError: expected string or bytes-like object, got 'NoneType' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\__init__.py", line 33, in classFactory
    from .data_plotly import DataPlotly
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\data_plotly.py", line 36, in 
    from DataPlotly.processing.dataplotly_provider import DataPlotlyProvider
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\processing\dataplotly_provider.py", line 27, in 
    from DataPlotly.processing.dataplotly_scatterplot import DataPlotlyProcessingScatterPlot
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\processing\dataplotly_scatterplot.py", line 43, in 
    import pandas as pd
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\__init__.py", line 26, in 
    from pandas.compat import (
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\compat\__init__.py", line 27, in 
    from pandas.compat.pyarrow import (
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\compat\pyarrow.py", line 10, in 
    _palv = Version(Version(pa.__version__).base_version)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\util\version\__init__.py", line 341, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'


Versione Python: 3.12.7 (main, Oct 25 2024, 11:18:09) [MSC v.1938 64 bit (AMD64)] 
Versione di QGIS: 3.40.1-Bratislava Bratislava, 989853a7 

Percorso Python:
C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Split-Lines-By-Points-main
C:/OSGeo4W/apps/qgis/./python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python312.zip
C:\OSGeo4W\apps\Python312\DLLs
C:\OSGeo4W\apps\Python312\Lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python312
C:\OSGeo4W\apps\Python312\Lib\site-packages
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32
C:\OSGeo4W\apps\Python312\Lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gensimplot
C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gensimplot
.
C:/Users/pigre/Desktop/progetto_overlap
```

<table width='100%' align='center'><tr><td>Versione di QGIS</td><td>3.40.1-Bratislava</td></tr><tr><td>Revisione codice QGIS</td><td><a href="https://github.com/qgis/QGIS/commit/989853a7">989853a7</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Librerie</b></td></tr><tr><td>Versione Qt</td><td>5.15.13</td></tr><tr><td>Versione Python</td><td>3.12.7</td></tr><tr><td>Versione GDAL/OGR</td><td>3.9.3</td></tr><tr><td>Versione PROJ</td><td>9.5.0</td></tr><tr><td>Versione database del Registro EPSG</td><td>v11.016 (2024-08-31)</td></tr><tr><td>Versione GEOS</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>Versione SQLite</td><td>3.46.1</td></tr><tr><td>Versione PDAL</td><td>2.8.1</td></tr><tr><td>Versione client PostgreSQL</td><td>16.2</td></tr><tr><td>Versione SpatiaLite</td><td>5.1.0</td></td></tr><tr><td>Versione QWT</td><td>6.3.0</td></tr><tr><td>Versione QScintilla2</td><td>2.14.1</td></tr><tr><td>Versione SO</td><td>Windows 11 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Plugins Python attivi</b></td></tr><tr><td>gensimplot</td><td>2.1</td></tr><tr><td>GroupStats</td><td>2.2.7</td></tr><tr><td>latlontools</td><td>3.7.2</td></tr><tr><td>nominatim_locator_filter</td><td>0.3.2</td></tr><tr><td>pointsamplingtool</td><td>0.5.4</td></tr><tr><td>qconsolidate</td><td>1.1.0</td></tr><tr><td>qduckdb</td><td>1.1.0</td></tr><tr><td>quick_map_services</td><td>0.19.36</td></tr><tr><td>Split-Lines-By-Points-main</td><td>1.0</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

The error also occurs on a new profile and as soon as I install it

**Comment by ghtmtt** [comment]
it's a problem of pyarrow that pandas is calling, see https://github.com/ghtmtt/DataPlotly/issues/363 where in the comments there are some temporary workarounds to solve the issue. Waiting for a new pyarrow packaging
