### ISSUE TITLE
No module named PyQt5.QtWebKit

### ISSUE THREAD

**Issue by sindile** [ghtmtt/DataPlotly#47]
Trying to install the plugin on QGIS 3 built from source I get the following error message - No module named PyQt5.QtWebKit
Running:

QGIS version | 2.99.0-Master | QGIS code revision | a0819053fd
-- | -- | -- | --
Compiled against Qt | 5.7.1 | Running against Qt | 5.7.1
Compiled against GDAL/OGR | 2.1.2 | Running against GDAL/OGR | 2.1.2
Compiled against GEOS | 3.5.1-CAPI-1.9.1 | Running against GEOS | 3.5.1-CAPI-1.9.1 r4246
PostgreSQL Client Version | 9.6.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.2 | PROJ.4 Version | 493
QScintilla2 Version | 2.9.3 | This copy of QGIS writes debugging output.

Any pointers what could be wrong?

**Comment by ghtmtt** [comment]
Very weird.
Could you paste the Stack Trace of python?
BTW: did you download the plugin from the Plugin Manager?

**Comment by sindile** [comment]
2017-09-15T16:50:08	WARNING	Traceback (most recent call last):
			  File "/home/zizi/gitrepo/qgis/QGIS/build/output/python/qgis/utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "/home/zizi/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/__init__.py", line 34, in classFactory
			    from .data_plotly import DataPlotly
			  File "/home/zizi/gitrepo/qgis/QGIS/build/output/python/qgis/utils.py", line 666, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/home/zizi/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly.py", line 30, in <module>
			    from .data_plotly_dialog import DataPlotlyDialog
			  File "/home/zizi/gitrepo/qgis/QGIS/build/output/python/qgis/utils.py", line 666, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "/home/zizi/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly_dialog.py", line 31, in <module>
			    from PyQt5.QtWebKit import QWebSettings
			  File "/home/zizi/gitrepo/qgis/QGIS/build/output/python/qgis/utils.py", line 666, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named 'PyQt5.QtWebKit'
Yes I am using the Plugin Manager

**Comment by ghtmtt** [comment]
mmm.. it seems you compiled QGIS **wihtout** `QWebKit`. You can verify it in the `CMakeCache.txt` file within your source folder. 

What about the line?

```
//Enable QtWebkit support
WITH_QTWEBKIT:BOOL=
```

**Comment by sindile** [comment]
Strange because it is enabled
//Enable QtWebkit support
WITH_QTWEBKIT:BOOL=TRUE

**Comment by ghtmtt** [comment]
It should be something wrong with your QGIS installation. I tested the plugin on several Linux machines and also Windows. Are you on OSX?

**Comment by sindile** [comment]
I am on Ubuntu 17.04

**Comment by ghtmtt** [comment]
do you have `python3-pyqt5.qtwebkit` installed?

**Comment by sindile** [comment]
Was missing python3-pyqt5.qtwebkit and plotly

**Comment by ghtmtt** [comment]
@sindile glad that you solved. actually linux users have to install `python3-plotly` by themselves. Windows users have the library already available.

I'll create a Wiki with some useful FAQ. 

Hope you will enjoy the plugin and report back other problems/suggestions
