### ISSUE TITLE
Webkit import error on install

### ISSUE THREAD

**Issue by millionpoundhat** [ghtmtt/DataPlotly#58]
I just installed 2.99 on linux 17.10. I tired to install the plugin and got the following error - 

Couldn't load plugin 'DataPlotly' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'PyQt5.QtWebKit' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/uncle/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/__init__.py", line 34, in classFactory
    from .data_plotly import DataPlotly
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/uncle/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly.py", line 30, in 
    from DataPlotly.data_plotly_dialog import DataPlotlyDockWidget
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/uncle/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly_dialog.py", line 31, in 
    from PyQt5.QtWebKit import QWebSettings
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PyQt5.QtWebKit'

**Comment by ghtmtt** [comment]
Hi, 

are you sure to have the qwebkit installed? 

`sudo apt-get install python3-pyqt5.qtwebkit`

**Comment by millionpoundhat** [comment]
Yes, that worked. I see qwebkit has been deprecated in favour of qwebengine. Thanks for the great plugin!
